export const CART_ADD_ARTICLE = "CART_ADD_ARTICLE";
export const CART_REMOVE_ARTICLE = "CART_REMOVE_ARTICLE";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";
