export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const ITEM_LIST_FAIL = "ITEM_LIST_FAIL";

export const ITEM_DETAILS_REQUEST = "ITEM_DETAILS_REQUEST";
export const ITEM_DETAILS_SUCCESS = "ITEM_DETAILS_SUCCESS";
export const ITEM_DETAILS_FAIL = "ITEM_DETAILS_FAIL";

export const ITEM_SAVE_REQUEST = "ITEM_SAVE_REQUEST";
export const ITEM_SAVE_SUCCESS = "ITEM_SAVE_SUCCESS";
export const ITEM_SAVE_FAIL = "ITEM_SAVE_FAIL";

export const ITEM_DELETE_REQUEST = "ITEM_SAVE_REQUEST";
export const ITEM_DELETE_SUCCESS = "ITEM_SAVE_SUCCESS";
export const ITEM_DELETE_FAIL = "ITEM_SAVE_FAIL";

export const ITEM_REVIEW_SAVE_REQUEST = "ITEM_REVIEW_SAVE_REQUEST";
export const ITEM_REVIEW_SAVE_SUCCESS = "ITEM_REVIEW_SAVE_SUCCESS";
export const ITEM_REVIEW_SAVE_FAIL = "ITEM_REVIEW_SAVE_FAIL";
export const ITEM_REVIEW_SAVE_RESET = "ITEM_REVIEW_SAVE_RESET";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
