export default {
  items: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: " Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },

    {
      _id: "2",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 125,
      brand: "Van Husen",
      rating: 4.5,
      numReviews: 5,
      countInStock: 10,
    },
    {
      _id: "5",
      name: "Church Suit",
      category: "Suits",
      image: "/images/p3.jpg",
      price: 125,
      brand: "Go Mai",
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
    },

    {
      _id: "5",
      name: "Church Suit",
      category: "Suits",
      image: "/images/p4.jpg",
      price: 125,
      brand: "Go Mai",
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
    },

    {
      _id: "5",
      name: "Church Suit",
      category: "Suits",
      image: "/images/p5.jpg",
      price: 125,
      brand: "Go Mai",
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
    },

    {
      _id: "5",
      name: "Church Suit",
      category: "Suits",
      image: "/images/p6.jpg",
      price: 125,
      brand: "Go Mai",
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
    },

    {
      _id: "5",
      name: "Church Suit",
      category: "Suits",
      image: "/images/p7.jpg",
      price: 125,
      brand: "Go Mai",
      rating: 4.5,
      reviews: 20,
      countInStock: 10,
    },
  ],
};
